namef=input("First name:")
namel=input("Last name:")
grade=int(input("Grade (9-12):"))
student_id=int(input('Student Id:'))
login_id=input('Login:')
GPA=float(input('GPA (0.0-4.0):'))
print(f'Your information:\n\tlogin:{login_id}\n\tId:{student_id}\n\tName:{namel}{namef}\n\tGPA:{GPA}\n\tGrade:{grade}')
