educational_details=[{"study":"b.tech",
                      "Institute":"cape",
                      "semester_marks":[{"semester_name":1,
                                         "subject":["computer programming","maths1","data science"],
                                         "semester_grade":"A"},
                                         {"semester_name":2,
                                         "subject":["oops","maths2","data science"],
                                         "semester_grade":"b+"},
                                         {"semester_name":3,
                                         "subject":["physics","maths","data science"],
                                         "semester_grade":"A+"},
                                         {"semester_name":4,
                                         "subject":["computer programming","maths new","data science"],
                                         "semester_grade":"B"}]},
                     {"study":"English",
                      "Institute":"anna university",
                      "semester_marks":[{"semester_name":1,
                                         "subject":["American english","phonetics","communicative english"],
                                         "semester_grade":"A"},
                                         {"semester_name":2,
                                         "subject":["comparative literature","russian literature","english"],
                                         "semester_grade":"b+"},
                                         {"semester_name":3,
                                         "subject":["literature","shakespeare","indian writing"],
                                         "semester_grade":"A+"},
                                         {"semester_name":4,
                                         "subject":["shakespeare1","drama","poetry"],
                                         "semester_grade":"A"}]},
                        {"study":"Maths",
                      "Institute":"cape",
                      "semester_marks":[{"semester_name":1,
                                         "subject":["maths1","arithemitic","physics"],
                                         "semester_grade":"A"},
                                         {"semester_name":2,
                                         "subject":["oops","maths2","physics1"],
                                         "semester_grade":"b+"},
                                         {"semester_name":3,
                                         "subject":["physics","maths","data science"],
                                         "semester_grade":"A+"},
                                         {"semester_name":4,
                                         "subject":["computer programming","maths new","data science"],
                                         "semester_grade":"B+"}]}]
                                 
                                      
                                        